jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:ps+uVDGFDJg9q3pLGLljMIuiTPFfNn+kmI+03S/0W+Wwnt8Dd+oVsmKRfYfmRNXqDRKGBkvOPFmti53lhlWCLPzPWUm5Xg==,iv:JmgI5jn4fMd7/OV2jjA8Jd7e1qrX58shQrYk2EgCbs8=,tag:t8Uv/SekzpTU9pHQTp3ZlA==,type:str]
jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:IhnTYctQahQA1BAlGBPA,iv:LXfspfGa8fst9OOsQtaj/19NcJ0FNQcwRKBCPT9vlpY=,tag:bzkZ3aY+YnKCXm+FEsJjRg==,type:str]
        client_secret: ENC[AES256_GCM,data:BlADDM0u6ldRSGAJCFqLew==,iv:dwdtAH9fAkNGmDZ6faqw/jSOObJJNR6GHbeCdy3KH50=,tag:NEEmYErHGw+GCk5OvBII2A==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:5lyHqCoT/4v6xjyrWizeSFoPGT0=,iv:nOdNYcKK657O4iqy/0NLgDrzGCEhMUEDQY0isg36SrU=,tag:CRcrDq+I8SUZgKrDo4MtNw==,type:str]
        client_secret: ENC[AES256_GCM,data:wHZFkDEaGoMPHhnaBBua35wr36Q+Z5yxZaO75rX+GUZCrZxWbYLe3g==,iv:0v2Ev2dxKb7euHQiHKHyjpIU+xV5OGcuO32+oGt9vqQ=,tag:Wt+MtL//fjHQh2vlk30GLA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:XDAZUSJpoMVQZs8EL7H1EQJYsEeOXTnReGo+Wh82bUAtg9rJzd+H793YP0KJ4ManxPasWolvjcPA7treCXpqGEb3YNMZa29tgCssc5SOIKLn9m+nvfc=,iv:E1xurwR9C969l8X9Wn0JXVcnsxNKPzWEQHMGKOF2Ueg=,tag:kkI4fEG70fb5NxuaxaRQvg==,type:str]
        stringData: ENC[AES256_GCM,data:oRqF8/m3leDZz3CRlk7k+ib9Wh6mjujNnL/iLlTGIk0SoS31QTYdRuxqlBL82K4s4UjTCD4jxKuhiCYf+b0ugKoz29LbHw0cWhTPrY7fYRCaJms2yDrK5mtEcPWP5LQuaPmkZgzxeSF/+Y7rNV93i8Sh/Fx9jY7X/AN+QrldE5BJmXN3ewyxZ1yWMDQk6EI88q96gVO2cACUpZiQ3S2dLFBGt5Vhbn+o1fMJSYZ16ZeeTmAL6Uj/XaDtmFhqX/IRP1zKA16Q8sR08GIjaVCW/BPZQLhDB/AYFCH7KrXzkZuZctgZzSBOqodiSGcTx9diVHsMg6UvTzNIkofh4hvooAgo4JHUBxl4oGO8br4HmB5+8fFTldK/EcqzslT1wT9nzsHMO0lFQxpi1f5tmwZNA4JIOPxJ+26ejLWANZzkVqBVvDg7MUQECtst0F/QUukSKHKeGiEQTXrO77Gkb8OoYJp61CqDidf0NHtSZ5aSYaNGE0fT84AmkhjIEtTlProPIYja3pLB0bsyWZ+SAo/YKSIDRgbUJwSlxLOvzUPNULdYaLosoMHGo8erFksrdwgEkF9i/ep1e4MCuB2OlUfo//UKO2ecMXYmWyhl9HBFoylAtrIFyqnr+b3BqyuOrf7i/Xq2RipxJFgfofM6YeLuOHj5/u7AQE4sHduRsK4=,iv:XElokyJkdDcQjacceri5yCUrpVQJ8Q4tIQfazCDSUSM=,tag:KOiGMs55m6pr0MzpNBrlHA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:42Z'
    enc: CiUA4OM7eKYwv5CrwTKrkzZOwFxZekXCP4ACmr8QeY3AVJKhFLgkEkkAsHDEl/dGKx2MOcU1EasGV3xddItQT1N063a+KbpiblIff2NblN0a2vA8vDmaTu8aD6PFT/sr6jN+Q5IgEBpb/5iUX5nwp44w
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:43Z'
  mac: ENC[AES256_GCM,data:Xx3oQEnGuVzv15pU5loH6gA1arkubVlJ4cixNMlB1lGW+A0qsuyPZ4+VaGiyCHzczDS/Ac93NXhQqpOj62JrbohDULBl3m9nSA2tVk7ueTYm+b3dZPjjbDN2HpZQ5jdAJMoL7lyAzYPEsaxeaLOGKurD1u4WzKFBbiFP/skLnpQ=,iv:/pgSEz0MILQ+zfm6g1lhDYQBpXoWz7DSC4aGkBF0t/U=,tag:QweF20DoZNPoQGlV/w+Fvg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
